route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
        auth_username: 'AKKA123456789RWVC'
        auth_password: "BEgx12308hfygstvckwefut378rthi0Q+hI"
        from: 'kalpanareddyneelapu@gmail.com'
        to: 'kalpananeelapu90@gmail.com'
        headers:
          subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']